### ISSUE TITLE
NPE During installation of oomph-task-cli

### ISSUE THREAD

**Issue by maybeec** [themetalone/oomph-fork#11]
on linux:
```
Repository http://maybeec.github.io/oomph-task-cli/update
java.lang.NullPointerException
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.getProfile(P2TaskImpl.java:793)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:671)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3151)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3079)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3060)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2960)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:556)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:682)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by themetalone** [comment]
should be fixed
